version: '2'
services:
    location2-app:
        image: location2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://location2-mysql:3306/location2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    location2-mysql:
        extends:
            file: mysql.yml
            service: location2-mysql
